# Configuration file for the Pull Request Labeler bot

# Add `new icon` label when there is an SVG added to the icons/ directory
"new icon":
  - on: added
  - icons/*.svg

# Add `icon outdated` label when there is an SVG modified to the icons/ directory
"icon outdated":
  - on: modified
  - icons/*.svg
